add cas & first ecu info + ordered parts

diff --git a/.github/workflows/detect-exif.yml b/.github/workflows/detect-exif.yml
--- a/.github/workflows/detect-exif.yml
+++ b/.github/workflows/detect-exif.yml
@@ -10,22 +10,25 @@ jobs:
       - uses: actions/checkout@v6
       
       - name: Install exiftool
-        run: sudo apt-get install -y exiftool
+        run: pip install detect-exif --break-system-packages
       
       - name: Scan for EXIF data in images
         run: |
-          EXIT_CODE=0
-          for file in $(find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.tiff" \) ! -path "./.git/*"); do
-            if exiftool "$file" | grep -q .; then
-              echo "ERROR: EXIF data found in $file"
-              exiftool "$file"
-              EXIT_CODE=1
+            EXIT_CODE=0
+            while read -rd $'\0' file; do
+                ERR=0
+                echo "Scanning $file for EXIF data..."
+                detect-exif --quiet "$file" || ERR=1
+                if [ $ERR -ne 0 ]; then   
+                echo "ERROR: EXIF data found in $file"
+                #   detect-exif "$file"
+                EXIT_CODE=1
+                fi
+            done < <(find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.tiff" \) ! -path "./.git/*" -print0 )
+
+            if [ $EXIT_CODE -eq 1 ]; then
+                echo "❌ Workflow failed: Image files contain EXIF data"
+                exit 1
+            else
+                echo "✅ No EXIF data found in image files"
             fi
-          done
-          
-          if [ $EXIT_CODE -eq 1 ]; then
-            echo "❌ Workflow failed: Image files contain EXIF data"
-            exit 1
-          else
-            echo "✅ No EXIF data found in image files"
-          fi
